/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import daos.MotocycleDAO;
import dtos.Brand;
import dtos.Motocycle;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author TanNV
 */
public class Management_Motocycle extends javax.swing.JFrame {

    BrandTable brandModel = null;
    MotoTable motoModel = null;
    boolean brandAddNew = true;
    boolean motoAddNew = true;

    /**
     * Creates new form Management
     */
    public Management_Motocycle() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        brandModel = new BrandTable();
        motoModel = new MotoTable();
        setModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBrand = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnBrandAddNew = new javax.swing.JButton();
        btnBrandSave = new javax.swing.JButton();
        btnBrandDelete = new javax.swing.JButton();
        txtBrandID = new javax.swing.JTextField();
        txtBrandName = new javax.swing.JTextField();
        txtBrandCountry = new javax.swing.JTextField();
        txtBrandDesc = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMoto = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMotoID = new javax.swing.JTextField();
        txtMotoModel = new javax.swing.JTextField();
        txtMotoCondition = new javax.swing.JTextField();
        txtMotoPrice = new javax.swing.JTextField();
        txtMotoQuantity = new javax.swing.JTextField();
        txtMotoWarranty = new javax.swing.JTextField();
        btnMotoAddNew = new javax.swing.JButton();
        btnMotoSave = new javax.swing.JButton();
        btnMotoDelete = new javax.swing.JButton();
        boxBrand = new javax.swing.JComboBox<>();
        calMotoYear = new com.toedter.calendar.JYearChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Motocycle Management");
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)), "Main part :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 0, 204))); // NOI18N

        tblBrand.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBrand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBrandMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBrand);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)), "Detail part :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 0, 204))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(51, 0, 204));

        jLabel9.setText("Brand ID :");

        jLabel10.setText("Brand name :");

        jLabel11.setText("Country :");

        jLabel12.setText("Description : ");

        btnBrandAddNew.setText("Add new");
        btnBrandAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandAddNewActionPerformed(evt);
            }
        });

        btnBrandSave.setText("Save");
        btnBrandSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandSaveActionPerformed(evt);
            }
        });

        btnBrandDelete.setText("Delete");
        btnBrandDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnBrandAddNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(btnBrandSave, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBrandID)
                            .addComponent(txtBrandName)
                            .addComponent(txtBrandCountry)
                            .addComponent(txtBrandDesc))))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btnBrandDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtBrandID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(jLabel10))
                    .addComponent(txtBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtBrandCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtBrandDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrandAddNew)
                    .addComponent(btnBrandSave))
                .addGap(18, 18, 18)
                .addComponent(btnBrandDelete)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Brand", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)), "Main part :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(51, 0, 204))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setForeground(new java.awt.Color(0, 0, 153));

        tblMoto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tblMoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMotoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMoto);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)), "Detail part : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel1.setText("Motocycle ID : ");

        jLabel2.setText("Model :");

        jLabel3.setText("Year :");

        jLabel4.setText("Condition :");

        jLabel5.setText("Price :");

        jLabel6.setText("Quantity :");

        jLabel7.setText("Warranty :");

        jLabel8.setText("Brand name :");

        btnMotoAddNew.setText("Add New");
        btnMotoAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotoAddNewActionPerformed(evt);
            }
        });

        btnMotoSave.setText("Save");
        btnMotoSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotoSaveActionPerformed(evt);
            }
        });

        btnMotoDelete.setText("Delete");
        btnMotoDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotoDeleteActionPerformed(evt);
            }
        });

        boxBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMotoID)
                            .addComponent(txtMotoModel)
                            .addComponent(txtMotoCondition)
                            .addComponent(txtMotoPrice)
                            .addComponent(txtMotoQuantity)
                            .addComponent(txtMotoWarranty)
                            .addComponent(boxBrand, 0, 198, Short.MAX_VALUE)
                            .addComponent(calMotoYear, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnMotoAddNew)
                        .addGap(27, 27, 27)
                        .addComponent(btnMotoSave, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMotoDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMotoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMotoModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calMotoYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMotoCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMotoPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMotoQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMotoWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(boxBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMotoAddNew)
                    .addComponent(btnMotoSave)
                    .addComponent(btnMotoDelete))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Motocycle", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrandSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandSaveActionPerformed
        // TODO add your handling code here:
        if (!validBrand()) { //check validation of brand input
            return;
        }
        try {
            String brandID = txtBrandID.getText().trim();
            String brandName = txtBrandName.getText().trim();
            String country = txtBrandCountry.getText().trim();
            String desc = txtBrandDesc.getText().trim();
            Brand brand = new Brand(brandID, brandName, country, desc);
            if (brandAddNew == true) { // case for insert new brand
                brandModel.createBrand(brand);
            }else{
                brandModel.updateBrand(brand);
            }
            tblBrand.updateUI();
            setBrandDefault();    // reset all of field
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error");
        }

    }//GEN-LAST:event_btnBrandSaveActionPerformed

    private void tblBrandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBrandMouseClicked
        // TODO add your handling code here:
        int indexSelected = tblBrand.getSelectedRow();
        if (indexSelected == -1) {
            return;
        }
        Brand brand = brandModel.getData().get(indexSelected);
        showBrand(brand);
    }//GEN-LAST:event_tblBrandMouseClicked

    private void tblMotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMotoMouseClicked
        // TODO add your handling code here:
        int indexSelected = tblMoto.getSelectedRow();
        if (indexSelected == -1) {
            return;
        }
        Motocycle moto = motoModel.getData().get(indexSelected);
        showMoto(moto);
    }//GEN-LAST:event_tblMotoMouseClicked

    private void btnBrandDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandDeleteActionPerformed
        // TODO add your handling code here:
        int indexSelected = tblBrand.getSelectedRow();
        if (indexSelected < 0) {
            JOptionPane.showMessageDialog(this, "Function invalid");
            return ;
        }
        try{
            // check number motocycle existed with brand ID
            MotocycleDAO motoDAO = new MotocycleDAO();
            String brandID = brandModel.getData().get(indexSelected).getBrandID();
            int contain = motoDAO.numberOfMotoByBrandID(brandID);  // number of moto contain with brandID
            if (contain == 0) {  // don't have any moto contain by brandID
                // delete brandID
                int option = JOptionPane.showConfirmDialog(this, "Are you sure to delete !!!");
                if (option == JOptionPane.OK_OPTION) {
                    brandModel.deleteBrand(brandID);
                    tblBrand.updateUI();
                }
            }else{
                JOptionPane.showMessageDialog(this, "The system existed " + contain + "motocycle \n Cannot delete !!!");
            }
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Delete is error");
        }
    }//GEN-LAST:event_btnBrandDeleteActionPerformed

    private void btnMotoAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotoAddNewActionPerformed
        // TODO add your handling code here:
        setMotoDefault();
    }//GEN-LAST:event_btnMotoAddNewActionPerformed

    private void btnMotoSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotoSaveActionPerformed
        // TODO add your handling code here:
        if (!validMoto()) {
            return ;
        }
        try{
            String motoID = txtMotoID.getText().trim();
            String model = txtMotoModel.getText().trim();
            int year = calMotoYear.getYear();
            String condition = txtMotoCondition.getText().trim();
            float price = Float.parseFloat(txtMotoPrice.getText().trim());
            int quantity = Integer.parseInt(txtMotoQuantity.getText().trim());
            String warranty = txtMotoWarranty.getText().trim();
            Brand brand = (Brand)boxBrand.getSelectedItem();
            Motocycle moto = new Motocycle(motoID, model, condition, warranty, year, price, quantity, brand);
            if (motoAddNew == true) { // insert new moto
                motoModel.createMoto(moto);
            }else{   // update moto
                motoModel.updateMoto(moto);
            }
            tblMoto.updateUI();
            setMotoDefault();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnMotoSaveActionPerformed

    private void btnMotoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotoDeleteActionPerformed
        // TODO add your handling code here:
        int indexSelected = tblMoto.getSelectedRow();
        if (indexSelected < 0) {
            JOptionPane.showMessageDialog(this, "Function invalid");
            return;
        }
        try{
            int option = JOptionPane.showConfirmDialog(this, "Are you sure to delete !!!");
            if (option == JOptionPane.OK_OPTION) {
                String motoID = motoModel.getData().get(indexSelected).getMotocycleID();
                motoModel.deleteMoto(motoID);
                tblMoto.updateUI();
                setMotoDefault();
            }
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_btnMotoDeleteActionPerformed

    private void btnBrandAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandAddNewActionPerformed
        // TODO add your handling code here:
        setBrandDefault();
    }//GEN-LAST:event_btnBrandAddNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Management_Motocycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Management_Motocycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Management_Motocycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Management_Motocycle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Management_Motocycle().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Management_Motocycle.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxBrand;
    private javax.swing.JButton btnBrandAddNew;
    private javax.swing.JButton btnBrandDelete;
    private javax.swing.JButton btnBrandSave;
    private javax.swing.JButton btnMotoAddNew;
    private javax.swing.JButton btnMotoDelete;
    private javax.swing.JButton btnMotoSave;
    private com.toedter.calendar.JYearChooser calMotoYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblBrand;
    private javax.swing.JTable tblMoto;
    private javax.swing.JTextField txtBrandCountry;
    private javax.swing.JTextField txtBrandDesc;
    private javax.swing.JTextField txtBrandID;
    private javax.swing.JTextField txtBrandName;
    private javax.swing.JTextField txtMotoCondition;
    private javax.swing.JTextField txtMotoID;
    private javax.swing.JTextField txtMotoModel;
    private javax.swing.JTextField txtMotoPrice;
    private javax.swing.JTextField txtMotoQuantity;
    private javax.swing.JTextField txtMotoWarranty;
    // End of variables declaration//GEN-END:variables

    private void setModel() {
        tblBrand.setModel(brandModel); // set data into tbl brand
        tblMoto.setModel(motoModel);   // set data into tbl moto
        boxBrand.setModel(new DefaultComboBoxModel(brandModel.getData()));  // set value for combobox
    }

    private void setBrandDefault() {
        brandAddNew = true;   // ready to add new brand
        txtBrandID.setEditable(true);
        txtBrandID.setText("");
        txtBrandID.requestFocus();

        txtBrandName.setText("");
        txtBrandCountry.setText("");
        txtBrandDesc.setText("");
    }

    private void setMotoDefault() {
        motoAddNew = true; // ready to add new moto
        txtMotoID.setEditable(true);
        txtMotoID.setText("");
        txtMotoID.requestFocus();

        txtMotoModel.setText("");
        calMotoYear.setYear(2021);
        txtMotoCondition.setText("");
        txtMotoPrice.setText("");
        txtMotoQuantity.setText("");
        txtMotoWarranty.setText("");
        boxBrand.setSelectedIndex(0);

    }

    private void showBrand(Brand brand) {
        brandAddNew = false;   // ready to update brand
        txtBrandID.setEditable(false);
        txtBrandID.setText(brand.getBrandID());

        txtBrandName.setText(brand.getBrandName());
        txtBrandCountry.setText(brand.getCountry());
        txtBrandDesc.setText(brand.getDescription());
    }

    private void showMoto(Motocycle moto) {
        motoAddNew = false; // ready to update moto
        txtMotoID.setEditable(false);
        txtMotoID.setText(moto.getMotocycleID());

        txtMotoModel.setText(moto.getModel());

        calMotoYear.setYear(moto.getYear());

        txtMotoCondition.setText(moto.getCondition());
        txtMotoPrice.setText(moto.getPrice() + "");
        txtMotoQuantity.setText(moto.getQuantity() + "");
        txtMotoWarranty.setText(moto.getWarranty());
        boxBrand.setSelectedItem(moto.getBrandID());

    }

    private boolean validBrand() {
        if (brandAddNew == true) {
            String brandID = txtBrandID.getText().trim();
            if (!brandID.matches("[a-zA-Z0-9]{2,10}")) {
                JOptionPane.showMessageDialog(this, "Brand ID from 2-10 characters \nNone special chatacters");
                return false;
            }
        }
        String brandName = txtBrandName.getText().trim();
        if (brandName.length() < 2 || brandName.length() >= 50) {
            JOptionPane.showMessageDialog(this, "Brand name from 2-50 characters");
            return false;
        }
        String country = txtBrandCountry.getText().trim();
        if (country.length() < 2 || country.length() >= 50) {
            JOptionPane.showMessageDialog(this, "Brand country from 2-50 characters");
            return false;
        }
        String desc = txtBrandDesc.getText().trim();
        if (desc.length() < 2 || desc.length() >= 200) {
            JOptionPane.showMessageDialog(this, "Brand description from 2-200 characters");
            return false;
        }
        return true;
    }

    private boolean validMoto() {
        if (motoAddNew == true) {
            String motoID = txtMotoID.getText().trim();
            if (!motoID.matches("[a-zA-Z0-9]{2,10}")) {
                JOptionPane.showMessageDialog(this, "Motocycle ID from 2-10 characters \nNone special chatacters");
                return false;
            }
        }
        String model = txtMotoModel.getText().trim();
        if (model.length() < 2 || model.length() >= 50) {
            JOptionPane.showMessageDialog(this, "Model name from 2-50 characters");
            return false;
        }
        String condition = txtMotoCondition.getText().trim();
        if (condition.length() < 2 || condition.length() >= 50) {
            JOptionPane.showMessageDialog(this, "Condition from 2-50 characters");
            return false;
        }
        int year = calMotoYear.getYear();
        if ((LocalDate.now().getYear() - year) < 0) {
            JOptionPane.showMessageDialog(this, "Year invalid");
            return false;
        }
        try {   // check price
            float price = Float.parseFloat(txtMotoPrice.getText().trim());
            if (price <= 0) {
                JOptionPane.showMessageDialog(this, "Price required is postitive number");
                return false;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Price required is positive number");
            return false;
        }

        try {   // check quantity
            int quantity = Integer.parseInt(txtMotoQuantity.getText().trim());
            if (quantity <= 0) {
                JOptionPane.showMessageDialog(this, "Quantity required is integer postitive number");
                return false;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Quantity required is integer positive number");
            return false;
        }

        String warranty = txtMotoWarranty.getText().trim();
        if (warranty.length() < 2 || warranty.length() >= 50) {
            JOptionPane.showMessageDialog(this, "Warranty from 2-50 characters");
            return false;
        }

        return true;
    }
    
}
